# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70


[[main]]
  identifier= "FX_reference"
  name = "FX Reference"
  weight = 80

[[main]]
  name = "Overview"
  parent= "FX_reference"
  url = "/doc/fx_reference/"
  weight = 5

[[main]]
  name = "What?"
  parent= "FX_reference"
  url= "/doc/fx_reference/what/"
  weight = 10

[[main]]
  name = "Who?"
  parent= "FX_reference"
  url= "/doc/fx_reference/who/"
  weight = 20

[[main]]
  name = "Why?"
  parent= "FX_reference"
  url= "/doc/fx_reference/why/"
  weight = 30

[[main]]
  name = "Where?"
  parent= "FX_reference"
  url= "/doc/fx_reference/where/"
  weight = 40

[[main]]
  name = "When?"
  parent= "FX_reference"
  url= "/doc/fx_reference/when/"
  weight = 50

[[main]]
  name = "How?"
  parent= "FX_reference"
  url= "/doc/fx_reference/how/"
  weight = 60

[[main]]
  identifier= "External_Reference"
  name = "External references"
  weight = 100

[[main]]
  parent= "External_Reference"
  name = "Data"
  weight = 10

[[main]]
  parent= "External_Reference"
  name = "Books & Papers"
  weight = 20

[[main]]
  parent= "External_Reference"
  name = "Glossary"
  weight = 30




